language: java
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn deploy
- '[[ $TRAVIS_TAG == v[0-9.]* ]] && { mvn clean deploy -Prelease; };'
before_install:
- openssl aes-256-cbc -K $encrypted_5c75f4681da2_key -iv $encrypted_5c75f4681da2_iv
  -in travis.gpg.enc -out travis.gpg -d
- openssl aes-256-cbc -K $encrypted_82a7a4aaf212_key -iv $encrypted_82a7a4aaf212_iv
  -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml
notifications:
  email:
  - arena-uqbar@googlegroups.com
