language: java
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && mvn deploy
- '[[ $TRAVIS_TAG == v[0-9.]* ]] && { mvn clean deploy -Prelease; };'
before_install:
- openssl aes-256-cbc -K $encrypted_5c75f4681da2_key -iv $encrypted_5c75f4681da2_iv
  -in maven_files.tar.enc -out maven_files.tar -d
- tar xvf maven_files.tar
- gpg --import travis.gpg
- mv settings.xml ~/.m2/settings.xml
notifications:
  email:
  - arena-uqbar@googlegroups.com
